-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 00:13:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema compare_cabins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compare_cabins
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compare_cabins` DEFAULT CHARACTER SET latin1 ;
USE `compare_cabins` ;
DROP TABLE IF EXISTS amenities, cabin, user, availability, cabin_picture, feature, rent_record, review;

-- -----------------------------------------------------
-- Table `compare_cabins`.`amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`amenities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `has_lake` TINYINT(4) NULL DEFAULT NULL,
  `has_river` TINYINT(4) NULL DEFAULT NULL,
  `has_pool` TINYINT(4) NULL DEFAULT NULL,
  `has_hot_tub` TINYINT(4) NULL DEFAULT NULL,
  `has_wifi` TINYINT(4) NULL DEFAULT NULL,
  `has_air_conditioning` TINYINT(4) NULL DEFAULT NULL,
  `has_washer_dryer` TINYINT(4) NULL DEFAULT NULL,
  `allows_pets` TINYINT(4) NULL DEFAULT NULL,
  `allows_smoking` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compare_cabins`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compare_cabins`.`cabin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`cabin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `descripiton` VARCHAR(255) NULL DEFAULT NULL,
  `bedroom_count` INT(11) NULL DEFAULT NULL,
  `bath_count` INT(11) NULL DEFAULT NULL,
  `maxOccupancy` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `amenities_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `amenities_id_idx` (`amenities_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_cabin_amenities`
    FOREIGN KEY (`amenities_id`)
    REFERENCES `compare_cabins`.`amenities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cabin_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `compare_cabins`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compare_cabins`.`availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`availability` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` FLOAT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `cabin_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cabin_id_idx` (`cabin_id` ASC),
  CONSTRAINT `availability_ibfk_1`
    FOREIGN KEY (`cabin_id`)
    REFERENCES `compare_cabins`.`cabin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compare_cabins`.`cabin_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`cabin_picture` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(255) NULL DEFAULT NULL,
  `cabin_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cabin_id_idx` (`cabin_id` ASC),
  CONSTRAINT `cabin_picture_ibfk_1`
    FOREIGN KEY (`cabin_id`)
    REFERENCES `compare_cabins`.`cabin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compare_cabins`.`feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`feature` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `feature_string` VARCHAR(255) NULL DEFAULT NULL,
  `cabin_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cabin_id_idx` (`cabin_id` ASC),
  CONSTRAINT `cabin_id`
    FOREIGN KEY (`cabin_id`)
    REFERENCES `compare_cabins`.`cabin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compare_cabins`.`rent_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`rent_record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `total_price` FLOAT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `cabin_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rent_record_cabin_idx` (`cabin_id` ASC),
  INDEX `fk_rent_record_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_rent_record_cabin`
    FOREIGN KEY (`cabin_id`)
    REFERENCES `compare_cabins`.`cabin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rent_record_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `compare_cabins`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compare_cabins`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compare_cabins`.`review` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `num_stars` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `rent_record_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_rent_record_idx` (`rent_record_id` ASC),
  CONSTRAINT `fk_review_rent_record`
    FOREIGN KEY (`rent_record_id`)
    REFERENCES `compare_cabins`.`rent_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
